name: pdm
description: A new Flutter project.
 
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
    
  provider:
  shared_preferences:

  cupertino_icons: ^1.0.2
  http: ^0.13.4
  flutter_modular: ^4.4.0
  localization: ^2.1.0
  flutter_svg: ^1.0.3
  mobx: ^2.0.6+1
  flutter_mobx: ^2.0.4
  google_maps_flutter: ^2.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  mobx_codegen: ^2.0.5+2
  build_runner: ^2.1.8
  flutter_lints: ^1.0.0

flutter:


  uses-material-design: true
  assets:
    - lib/assets/
    - lib/assets/i18n/
    - lib/assets/images/
    - lib/assets/fonts/

  fonts:
    - family: Asap
      fonts:
        - asset: lib/assets/fonts/Asap-Bold.ttf
          weight: 700
        - asset: lib/assets/fonts/Asap-Medium.ttf
          weight: 500
        - asset: lib/assets/fonts/Asap-Regular.ttf
          weight: 400

